### PR TITLE
Performance overhaul

### LINKED ISSUE #129: Checking for updates while editing package.json
### What is the issue?

When I update dependencies in a project with a few dependencies it starts rechecking for updates/deprecations and I cannot continue updating dependencies until it finishes.

See this video (quick fix popovers are not visible due to window capture recording)
https://github.com/user-attachments/assets/120e64b6-5184-438b-b7a4-82c874ad520d

### What are the steps to reproduce this issue?

You can reproduce this in this project & commit: https://github.com/Samedis-care/identity-management-frontend/tree/d054598b6bcd6654cd103c93a59373f9abe72b7e

### What were you expecting to happen?

Highlights don't disappear and I can continue with quick fix actions to update the dependencies

### Paste any relevant logs, error output, etc.

_No response_

### What OS are you experiencing the problem on?

Linux

### Additional platform information

```
WebStorm 2024.3 EAP
Build #WS-243.12818.48, built on September 11, 2024
Runtime version: 21.0.4+8-b589.3 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.X11.XToolkit
Linux 6.6.51-1-lts
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 8192M
Cores: 16
Registry:
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  com.github.warningimhack3r.npmupdatedependencies (3.0.2)
  com.eny.i18n (2.6.2)
Current Desktop: KDE
```

### Duplicates

- [X] I have checked that my problem has not already been mentioned recently in an existing issue

### LINKED ISSUE #130: Does not ignore non NPM dependencies
### What is the issue?

Some dependencies are distributed outside of NPM. A package.json can have the following entires for example:
```
  "components-care": "github:Samedis-care/react-components#master_dist",
  "xlsx": "https://cdn.sheetjs.com/xlsx-0.20.2/xlsx-0.20.2.tgz"
```

The plugin tries to check those for updates too.

For more information see https://docs.npmjs.com/cli/v6/configuring-npm/package-json#dependencies

### What are the steps to reproduce this issue?

Insert one of the above mentioned dependencies into the package.json and the plugin will ask the NPM registry for updates

### What were you expecting to happen?

The dependencies should just be ignored for now. You could add a feature later to support update checking in git repos (via git tags as explained in the NPM docs link above).

### Paste any relevant logs, error output, etc.

```
2024-09-17 21:21:01,361 [ 640901]   INFO - #com.github.warningimhack3r.npmupdatedependencies.backend.engine.PackageUpdateChecker - Checking for updates for xlsx with comparator https://cdn.sheetjs.com/xlsx-0.20.2/xlsx-0.20.2.tgz
2024-09-17 21:21:01,361 [ 640901]   WARN - #com.github.warningimhack3r.npmupdatedependencies.backend.engine.PackageUpdateChecker - Comparator https://cdn.sheetjs.com/xlsx-0.20.2/xlsx-0.20.2.tgz is not upgradable, removing cached versions for xlsx
```

```
2024-09-17 20:35:05,686 [2102804]   INFO - #com.github.warningimhack3r.npmupdatedependencies.backend.engine.PackageUpdateChecker - Checking for updates for components-care with comparator github:Samedis-care/react-components#master_dist
2024-09-17 20:35:05,686 [2102804]   WARN - #com.github.warningimhack3r.npmupdatedependencies.backend.engine.PackageUpdateChecker - Comparator github:Samedis-care/react-components#master_dist is not upgradable, removing cached versions for components-care
```

### PR DESCRIPTION
**Pull request by WarningImHack3r**
Fixes #129
Fixes #130

As reported in the 2 issues @SCjona opened, there is room for improvement in how the plugin handles its cache and scan triggers.

This PR addresses all 5 reported issues and will be a minor update to the plugin.

## Improvements
- [x] Cache "no deprecation" and "no update" (#129)
- [x] Cache values checked upon for updates and deprecations, invalidate on change (#129)
- [x] Invalidate cache after a configurable amount of time (10 min by default?) (#129)
- [x] Check for a valid comparator before checking for deprecations (#130)
- [x] Improve the ignored patterns list (#130)

### CODE REVIEW

**Comment by WarningImHack3r** [comment]
@SCjona thanks for testing! Yeah I know I have some logic flaws I need to fix, that’s why I didn’t merge yet
I just implemented the stuff without really trying it out :D

**Comment by WarningImHack3r** [comment]
I decently tested everything and damn, it's DRASTICALLY faster!!

**Comment by SCjona** [comment]
thanks, this is way better, but there's still room for improvement :D

<details>
<summary> you could implement a time based HTTP cache </summary>

```
2024-09-26 11:33:07,754 [ 145098]   FINE - #com.github.warningimhack3r.npmupdatedependencies.backend.engine.NPMJSClient - HTTP GET https://registry.npmjs.org/@mui/icons-material/latest
2024-09-26 11:33:08,436 [ 145780]   FINE - #com.github.warningimhack3r.npmupdatedependencies.backend.engine.NPMJSClient - HTTP GET https://registry.npmjs.org/@mui/icons-material/latest
2024-09-26 11:33:13,038 [ 150382]   FINE - #com.github.warningimhack3r.npmupdatedependencies.backend.engine.NPMJSClient - HTTP GET https://registry.npmjs.org/@mui/material/latest
2024-09-26 11:33:13,732 [ 151076]   FINE - #com.github.warningimhack3r.npmupdatedependencies.backend.engine.NPMJSClient - HTTP GET https://registry.npmjs.org/@mui/material/latest
2024-09-26 11:33:14,304 [ 151648]   FINE - #com.github.warningimhack3r.npmupdatedependencies.backend.engine.NPMJSClient - HTTP GET https://registry.npmjs.org/@types/node/latest
2024-09-26 11:33:15,235 [ 152579]   FINE - #com.github.warningimhack3r.npmupdatedependencies.backend.engine.NPMJSClient - HTTP GET https://registry.npmjs.org/@types/node/latest
2024-09-26 11:33:16,330 [ 153674]   FINE - #com.github.warningimhack3r.npmupdatedependencies.backend.engine.NPMJSClient - HTTP GET https://registry.npmjs.org/@types/react-signature-canvas/latest
2024-09-26 11:33:17,024 [ 154368]   FINE - #com.github.warningimhack3r.npmupdatedependencies.backend.engine.NPMJSClient - HTTP GET https://registry.npmjs.org/@types/react-signature-canvas/latest
2024-09-26 11:33:19,101 [ 156445]   FINE - #com.github.warningimhack3r.npmupdatedependencies.backend.engine.NPMJSClient - HTTP GET https://registry.npmjs.org/libphonenumber-js/latest
2024-09-26 11:33:19,603 [ 156947]   FINE - #com.github.warningimhack3r.npmupdatedependencies.backend.engine.NPMJSClient - HTTP GET https://registry.npmjs.org/libphonenumber-js/latest
```

</details>

you can also replace the ShellRunner with a simple HTTP request

`npm v nomnom deprecated --registry=https://registry.npmjs.org` is basically the same as `curl https://registry.npmjs.org/nomnom/latest | jq .deprecated` except that latter is twice as fast on my system and uses maybe 1/8 of the CPU time. combine that with the HTTP cache above and it's even faster (basically it will perform deprecation checking and update checking in one single request) although technically single versions can be deprecated in NPM, so always fetching the latest version (which i think NPM does too, as `npm help view` states that the default version if unspecified is latest) is not the correct thing to do, so probably there are still two requests needed.

**Comment by WarningImHack3r** [comment]
@SCjona thanks again for your help on that!

#### HTTP cache

Yes, it's absolutely a good idea - even though it looks ridiculously small compared to what's been done here :D

#### Don't use the shell commands

I originally did this because 1/ I never benchmarked it and I thought a local action would always be faster than a remote one and 2/ I didn't know the command actually made a remote request! (do you have a link to some docs for that?)

---
Can you please open one (or 2) issues for that? I have a new actually visible feature I plan to add, I could bundle all that in a 3.2.0! Thanks

**Comment by SCjona** [comment]
>  I didn't know the command actually made a remote request! (do you have a link to some docs for that?)

the command description is `npm-view - View registry info` if the registry is remote it will make an request to that.
it's not explicitly documented (and probably beyond the scope of an usage documentation) that it makes a remote request, but you can see it using sockets (if you're on linux `strace npm view @mui/material 2>&1 | grep socket` or `grep connect`). there is also no local caching, the socket is used every time the command is run, even if you specify a fixed version.

>  I never benchmarked it and I thought a local action would always be faster than a remote one

npm itself has quite an overhead. just running `npm help` takes 150ms on my system (nodejs hello world takes 30ms)

**Pull request merged**
